---

- hosts: all
  become: true
  
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_facts.distribution in ["Ubuntu", "Debian"]

  - name: install apache2 package
    apt: 
      name: apache2
      state: latest
    when: ansible_facts.distribution in ["Ubuntu", "Debian"]

  - name: add php support for apache
    apt: # comment here - will it mess this up?
      name: libapache2-mod-php
      state: latest
    when: ansible_facts.distribution in ["Ubuntu", "Debian"]
